-- Phase 4: persist RecipeCosting (the live "recipes"/Costing tab in
-- SalePurchaseTransactions.tsx), which today only lives in store.recipeCostings
-- (memory-only, never read from or written to Supabase).
--
-- RecipeCosting = { id, name, menuItems: string[], ingredients: RecipeIngredient[],
--   hotCupInventoryItemId?, icedCupInventoryItemId?, otherCupInventoryItemId? }
-- RecipeIngredient = { inventoryItemId, name, amount, unit }
--
-- menuItems supports custom names not present in menu_items (the UI's "Not on
-- the menu" flow), so recipe_costing_menu_items stores plain text, not a
-- menu_items FK. ingredients supports an "other" / no-inventory-link case
-- (ingredient.inventoryItemId is "" or the literal "other"), so
-- recipe_costing_ingredients.inventory_item_id is nullable; the application
-- reconstructs the "other" sentinel from "has a name but no inventory link"
-- (see readStore() in src/lib/store.ts) rather than storing it directly, since
-- that's already fully determined by the existing columns.
--
-- Cup/ingredient inventory references use ON DELETE SET NULL, not CASCADE:
-- deleting an inventory item must not silently destroy a recipe costing, only
-- clear that one reference (matching the Phase 1 principle for inventory
-- deletes). recipe_costing_menu_items/recipe_costing_ingredients use
-- ON DELETE CASCADE from their parent recipe_costings row, so deleting a
-- costing needs no RPC - a plain delete on the parent is already atomic.

create table if not exists public.recipe_costings (
  id text primary key,
  name text not null default '',
  hot_cup_inventory_item_id text references public.inventory_items(id) on delete set null,
  iced_cup_inventory_item_id text references public.inventory_items(id) on delete set null,
  other_cup_inventory_item_id text references public.inventory_items(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ingredientsForOrderLine() picks [...recipeCostings].reverse().find(...), i.e.
-- the LAST-inserted matching costing wins ties; created_at ordering on read
-- preserves that.
create index if not exists recipe_costings_created_at_idx on public.recipe_costings (created_at);

create table if not exists public.recipe_costing_menu_items (
  id bigint generated by default as identity primary key,
  recipe_costing_id text not null references public.recipe_costings(id) on delete cascade,
  menu_item_name text not null,
  created_at timestamptz not null default now()
);

create index if not exists recipe_costing_menu_items_costing_idx on public.recipe_costing_menu_items (recipe_costing_id, created_at);

create table if not exists public.recipe_costing_ingredients (
  id text primary key,
  recipe_costing_id text not null references public.recipe_costings(id) on delete cascade,
  inventory_item_id text references public.inventory_items(id) on delete set null,
  name text not null,
  amount numeric not null,
  unit text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists recipe_costing_ingredients_costing_idx on public.recipe_costing_ingredients (recipe_costing_id, created_at);

-- Atomic save: upsert the parent, replace its menu-item assignments, replace
-- its ingredient rows, all inside one function invocation (one transaction).
-- Mirrors save_costing from Phase 2 (20260917034533_costing_persistence.sql).
create or replace function public.save_recipe_costing(
  p_id text,
  p_name text,
  p_hot_cup_inventory_item_id text,
  p_iced_cup_inventory_item_id text,
  p_other_cup_inventory_item_id text,
  p_menu_items jsonb,
  p_ingredients jsonb
)
returns void
language plpgsql
as $$
begin
  if p_id is null or length(trim(p_id)) = 0 then
    raise exception 'save_recipe_costing: p_id is required';
  end if;
  if p_menu_items is null or jsonb_typeof(p_menu_items) <> 'array' then
    raise exception 'save_recipe_costing: p_menu_items must be a JSON array';
  end if;
  if p_ingredients is null or jsonb_typeof(p_ingredients) <> 'array' then
    raise exception 'save_recipe_costing: p_ingredients must be a JSON array';
  end if;

  insert into public.recipe_costings (
    id, name, hot_cup_inventory_item_id, iced_cup_inventory_item_id, other_cup_inventory_item_id
  )
  values (
    p_id,
    trim(coalesce(p_name, '')),
    nullif(trim(coalesce(p_hot_cup_inventory_item_id, '')), ''),
    nullif(trim(coalesce(p_iced_cup_inventory_item_id, '')), ''),
    nullif(trim(coalesce(p_other_cup_inventory_item_id, '')), '')
  )
  on conflict (id) do update
    set name = excluded.name,
        hot_cup_inventory_item_id = excluded.hot_cup_inventory_item_id,
        iced_cup_inventory_item_id = excluded.iced_cup_inventory_item_id,
        other_cup_inventory_item_id = excluded.other_cup_inventory_item_id,
        updated_at = now();

  delete from public.recipe_costing_menu_items where recipe_costing_id = p_id;
  insert into public.recipe_costing_menu_items (recipe_costing_id, menu_item_name)
  select p_id, trim(value)
  from jsonb_array_elements_text(p_menu_items) as value
  where trim(value) <> '';

  delete from public.recipe_costing_ingredients where recipe_costing_id = p_id;
  insert into public.recipe_costing_ingredients (id, recipe_costing_id, inventory_item_id, name, amount, unit)
  select
    p_id || '-ing-' || row_number() over (),
    p_id,
    nullif(nullif(trim(coalesce(elem->>'inventoryItemId', '')), ''), 'other'),
    trim(elem->>'name'),
    (elem->>'amount')::numeric,
    coalesce(nullif(trim(elem->>'unit'), ''), '')
  from jsonb_array_elements(p_ingredients) as elem
  where trim(coalesce(elem->>'name', '')) <> '';
end;
$$;

revoke all on function public.save_recipe_costing(text, text, text, text, text, jsonb, jsonb) from public;
revoke all on function public.save_recipe_costing(text, text, text, text, text, jsonb, jsonb) from anon;
revoke all on function public.save_recipe_costing(text, text, text, text, text, jsonb, jsonb) from authenticated;
grant execute on function public.save_recipe_costing(text, text, text, text, text, jsonb, jsonb) to service_role;

-- Tables created via the SQL editor / dashboard in this project were
-- auto-granted to anon/authenticated/service_role; tables created via plain
-- CREATE TABLE are not. Match the existing costings/costing_ingredients
-- grant pattern (verified via information_schema.table_privileges) so
-- src/lib/store.ts's service-role client can actually read/write these.
grant select, insert, update, delete on public.recipe_costings to anon, authenticated, service_role;
grant select, insert, update, delete on public.recipe_costing_menu_items to anon, authenticated, service_role;
grant select, insert, update, delete on public.recipe_costing_ingredients to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;
